# Generated by Django 5.1 on 2024-08-18 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='first_name',
            field=models.CharField(default='timezone.now', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=',/Image'),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='type',
            field=models.CharField(choices=[('General', 'General'), ('Manager', 'Manager')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
