# Generated by Django 5.1 on 2024-08-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_registrationmodel_date_registrationmodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registrationmodel',
            name='last_name',
        ),
    ]
