# Generated by Django 5.1 on 2024-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_registrationmodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='./Image'),
        ),
    ]
