# Generated by Django 5.1 on 2024-08-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_registrationmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='type',
            field=models.CharField(choices=[('General', 'General'), ('Staf', 'Staf'), ('Manager', 'Manager')], max_length=20),
        ),
    ]
