# Generated by Django 5.1 on 2024-08-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_registrationmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='./Image/Account'),
        ),
    ]
