# Generated by Django 5.1 on 2024-09-05 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_item', models.ManyToManyField(to='Product.productmodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
