# Generated by Django 5.1 on 2024-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmodel',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
