# Generated by Django 5.1 on 2024-09-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesProduct', '0002_alter_salesmodel_city_alter_salesmodel_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmodel',
            name='sales_item',
        ),
    ]
