# Generated by Django 5.1 on 2024-09-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesProduct', '0003_remove_salesmodel_sales_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmodel',
            name='sales_item',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
