# Generated by Django 5.1 on 2024-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '__first__'),
        ('SalesProduct', '0004_salesmodel_sales_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmodel',
            name='sales_item',
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='sales_item',
            field=models.ManyToManyField(to='Product.productmodel'),
        ),
    ]
